### ISSUE TITLE
🐞The new embedding does not support the old FlutterView

### ISSUE THREAD

**Issue by oligazar** [fluttercommunity/flutter_workmanager#178]
- [x] I have read the [README](https://github.com/vrtdev/flutter_workmanager/blob/master/README.md)
- [x] I have done the setup for [Android](https://github.com/vrtdev/flutter_workmanager/blob/master/ANDROID_SETUP.md)
- [x] I have done the setup for [iOS](https://github.com/vrtdev/flutter_workmanager/blob/master/IOS_SETUP.md)
- [x] I have ran the sample app and it does not work there

**Version**

| Technology           | Version       |
| -------------------  | ------------- |
| Workmanager version  |      ^0.2.2         |
| Xcode version        |        11.5       |
| Swift version        |       4        |
| iOS deployment target|      11.0         |

**Describe the error**
I followed [V1](https://github.com/vrtdev/flutter_workmanager/blob/master/ANDROID_SETUP_V1.md) setup guide as I cannot use V2 at the time. But I get `java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException: The new embedding does not support the old FlutterView`

`2020-06-09 16:35:31.387 13059-13135/com.agforce.driver.treckerflutter E/WM-WorkerWrapper: Work [ id=292dc02b-343f-4727-a4e0-356f60bf44b2, tags={ be.tramckrijte.workmanager.BackgroundWorker } ] failed because it threw an exception/error
    java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException: The new embedding does not support the old FlutterView.
        at androidx.work.impl.utils.futures.AbstractFuture.getDoneValue(AbstractFuture.java:516)
        at androidx.work.impl.utils.futures.AbstractFuture.get(AbstractFuture.java:475)
        at androidx.work.impl.WorkerWrapper$2.run(WorkerWrapper.java:284)
        at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.UnsupportedOperationException: The new embedding does not support the old FlutterView.
        at io.flutter.embedding.engine.plugins.shim.ShimRegistrar.view(ShimRegistrar.java:82)
        at io.flutter.plugins.webviewflutter.WebViewFlutterPlugin.registerWith(WebViewFlutterPlugin.java:49)
        at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:45)
        at com.agforce.driver.treckerflutter.Application.registerWith(Application.kt:21)
        at be.tramckrijte.workmanager.BackgroundWorker.startWork(BackgroundWorker.kt:80)
        at androidx.work.impl.WorkerWrapper$1.run(WorkerWrapper.java:267)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:172)
        at android.app.ActivityThread.main(ActivityThread.java:6590)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)`

**Output of `flutter doctor -v`**
`[✓] Flutter (Channel stable, v1.17.3, on Mac OS X 10.15.5 19F101, locale en-TH)
    • Flutter version 1.17.3 at /Users/Admin/flutter
    • Framework revision b041144f83 (5 days ago), 2020-06-04 09:26:11 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/Admin/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/Admin/Library/Android/sdk
    • Java binary at: /Applications/Android Studio 3.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.8.4

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio 3.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] IntelliJ IDEA Community Edition (version 2018.2.8)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
`

Any way to overcome the issue?

**Comment by ened** [comment]
hi @oligazar could you please retest this issue using the most recent version `0.4.0` and re-confirm this problem?
