### ISSUE TITLE
🐞[Android] Getting a MissingPluginException for method registerOneOffTask while trying to chain multiple background task

### ISSUE THREAD

**Issue by CaporalDead** [fluttercommunity/flutter_workmanager#187]
- [x] I have read the [README](https://github.com/vrtdev/flutter_workmanager/blob/master/README.md)
- [x] I have done the setup for [Android](https://github.com/vrtdev/flutter_workmanager/blob/master/ANDROID_SETUP.md)
- [x] I have done the setup for [iOS](https://github.com/vrtdev/flutter_workmanager/blob/master/IOS_SETUP.md)
- [x] I have ran the sample app and it does not work there

**Version**

| Technology           | Version       |
| -------------------  | ------------- |
| Workmanager version  |  0.2.3 |
| Flutter version | 1.17.1 |
| Dart version | 2.8.2 |

**Describe the error**

Android only.

I'm trying to chain multiple background task one after each other on an existing project by calling the `registerOneOffTask` from a `registerOneOffTask` call but I'm getting this error when I call the `registerOneOffTask` method from a background task.

The weird thing is that with minimum code, it works perfectly on a brand new project (both examples are available below).

```
E/flutter ( 6955): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method registerOneOffTask on channel be.tramckrijte.workmanager/foreground_channel_work_manager)
E/flutter ( 6955): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
E/flutter ( 6955): <asynchronous suspension>
E/flutter ( 6955): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
E/flutter ( 6955): #2      Workmanager.registerOneOffTask (package:workmanager/src/workmanager.dart:124:32)
E/flutter ( 6955): #3      BackgroundManager.run (package:mobile_race/services/background/BackgroundManager.dart:37:27)
E/flutter ( 6955): <asynchronous suspension>
E/flutter ( 6955): #4      Workmanager.executeTask.<anonymous closure> (package:workmanager/src/workmanager.dart:80:28)
E/flutter ( 6955): #5      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:409:55)
E/flutter ( 6955): #6      MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:377:54)
E/flutter ( 6955): #7      _DefaultBinaryMessenger.handlePlatformMessage (package:flutter/src/services/binding.dart:199:33)
E/flutter ( 6955): #8      _invoke3.<anonymous closure> (dart:ui/hooks.dart:290:15)
E/flutter ( 6955): #9      _rootRun (dart:async/zone.dart:1184:13)
E/flutter ( 6955): #10     _CustomZone.run (dart:async/zone.dart:1077:19)
E/flutter ( 6955): #11     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
E/flutter ( 6955): #12     _invoke3 (dart:ui/hooks.dart:289:10)
E/flutter ( 6955): #13     _dispatchPlatformMessage (dart:ui/hooks.dart:164:5)
E/flutter ( 6955): 
I/WM-WorkerWrapper( 6955): Worker result SUCCESS for Work [ id=75ca11c8-9d75-426b-a5a4-7c2d2ccf4cd8, tags={ be.tramckrijte.workmanager.BackgroundWorker } ]
```

Code from my existing project : 

```dart
import 'package:hive/hive.dart';
import 'package:path_provider/path_provider.dart';
import 'package:workmanager/workmanager.dart';

class BackgroundManager {
  static Future<bool> run(taskName, Map<String, dynamic> inputData) async {
    Hive.init((await getApplicationDocumentsDirectory()).path);

    Box box = await Hive.openBox('queue');

    switch (taskName) {
      case "process":
        print("Processing first task of a new group [${inputData['group']}]");

        Map<String, dynamic> data = new Map<String, dynamic>.from(box.get(inputData['group']));
        AsyncEntry entry = AsyncEntry.fromMap(data);
        AsyncTask firstTask = entry.firstIncompleteTask();

        if (null != firstTask) {
          print("Scheduling next task [${firstTask.id}]");
          print("${firstTask.toMap()}");

          await Future.delayed(Duration(seconds: 10));

          try {
              Workmanager.registerOneOffTask(firstTask.id, firstTask.task, inputData: firstTask.toMap());
          } catch (e) {
            print("SCHEDULE ERROR $e");
          }
        }

        break;
      case "upload":
        try {
          UploadTask task = UploadTask.fromMap(inputData);

          print("Uploading for task [${task.id}] from group [${task.groupIdentifier}], path=[${task.path}]");
        } catch (e) {
          print(">>>> ERROR UPLOAD $e");
        }

        break;
      case "encode_video":
        EncodeVideoTask task = EncodeVideoTask.fromMap(inputData);

        print("Encoding video for task [${task.id}] from group [${task.groupIdentifier}], path=[${task.path}]");

        break;
    }

    return Future.value(true);
  }
}
```

The first call I do : 

```dart
    // ...
    Workmanager.registerOneOffTask(Uuid().v4(), "process", inputData: {
      'group': groupIdentifier,
    });
```

On a brand new project, the minimum code that works : 

```dart
import 'package:workmanager/workmanager.dart';

class BackgroundManager {
  static Future<bool> run(taskName, Map<String, dynamic> inputData) async {
    switch (taskName) {
      case "1":
        print("GOING 1");
        await Future.delayed(Duration(seconds: 10));
        Workmanager.registerOneOffTask("1", "2", inputData: {
          ...inputData,
          'from': 1,
          'to': 2,
        });
        break;
      case "2":
        print("GOING 2");
        await Future.delayed(Duration(seconds: 10));
        Workmanager.registerOneOffTask("2", "3", inputData: {
          ...inputData,
          'from': 2,
          'to': 3,
        });
        break;
      case "3":
        print("GOING 3");
        await Future.delayed(Duration(seconds: 10));
        print("DONE");
        break;
      default:
        print("Unknown [$taskName]");
        break;
    }

    return Future.value(true);
  }
}
```

And the first call I do : 

```dart
void _incrementCounter() {
    setState(() {
      _counter++;
      Workmanager.registerOneOffTask("coucou$_counter", "1", inputData: {
        "counter": _counter,
      });
    });
  }
```

**Output of `flutter doctor -v`**

```
[✓] Flutter (Channel stable, v1.17.1, on Linux, locale fr_FR.UTF-8)
    • Flutter version 1.17.1 at /home/thomas/flutter
    • Framework revision f7a6a7906b (il y a 9 semaines), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/thomas/Android/Sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /home/thomas/Android/Sdk
    • Java binary at:
      /home/thomas/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6626763/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Android Studio (version 4.0)
    • Android Studio at
      /home/thomas/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6626763
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.11.0

[✓] Connected device (1 available)
    • Pixel 4 XL • 192.168.0.14:5307 • android-arm64 • Android 10 (API 29)

• No issues found!
```

**Comment by wirasetiawan29** [comment]
Same issue found, using example project with xcode debug

```
2020-07-15 11:16:29.713569+0700 Runner[25165:221916] [VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method initialize on channel be.tramckrijte.workmanager/foreground_channel_work_manager)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
<asynchronous suspension>
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
#2      Workmanager.initialize (package:workmanager/src/workmanager.dart:100:30)
#3      _MyAppState.build.<anonymous closure> (package:workmanager_example/main.dart:87:33)
#4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:779:19)
#5      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:862:36)
#6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
#7      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:504:11)
#8      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:282:5)
#9      BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:217:7)
#10     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:475:9)
#11     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:76:12)
#12     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:122:9)
#13     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
#14     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:120:18)
#15     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:106:7)
#16     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
#17     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
#18     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
#19     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
#20     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
#21     _rootRunUnary (dart:async/zone.dart:1196:13)
#22     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#23     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
#24     _invoke1 (dart:ui/hooks.dart:275:10)
#25     _dispatchPointerDataPacket (dart:ui/hooks.dart:184:5)
```

**Comment by gebsl** [comment]
@wirasetiawan29: Possibly the same as #189?

**Comment by CaporalDead** [comment]
Not sure if it is @gebsl. I put more context below if you want to compare the call of the `initialize` method.

On my "complex app" that crashes, here's the main method :

```dart
void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await Workmanager.initialize(callbackDispatcher, isInDebugMode: kDebugMode);

  await SystemChrome.setEnabledSystemUIOverlays([
    SystemUiOverlay.bottom,
    SystemUiOverlay.top,
  ]);

  await SystemChrome.setPreferredOrientations([
    DeviceOrientation.portraitUp,
    DeviceOrientation.portraitDown,
  ]);

  Hive.init((await getApplicationDocumentsDirectory()).path);

  final appPreferences = await StreamingSharedPreferences.instance;

  await checkWipe(appPreferences);

  final appSettings = AppSettings(preferences: appPreferences);

  timeago.setLocaleMessages('fr_short', timeago.FrShortMessages());

  runApp(MyApp(appSettings));

  bg.BackgroundGeolocation.registerHeadlessTask(
    backgroundGeolocationHeadlessTask,
  );
  BackgroundFetch.registerHeadlessTask(
    backgroundFetchHeadlessTask,
  );
}
```

On the fresh app I built to test (that doesn't crash), here's the main method : 

```dart
void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await Workmanager.initialize(
      callbackDispatcher, // The top level function, aka callbackDispatcher
      isInDebugMode: true // If enabled it will post a notification whenever the task is running. Handy for debugging tasks
  );

  runApp(MyApp());
}
```

**Comment by gebsl** [comment]
@CaporalDead: I referred to @wirasetiawan29, as his/her error message seems to be the same as in #189 ;)

I think your problem is different from the one i mentioned in bug #189. But as it works in an example app, there has to be some difference in configuration in your complex app.

One thing you could try in your complex app is moving your call to Workmanager `Workmanager.registerOneOffTask(firstTask.id, firstTask.task, inputData: firstTask.toMap());` to the very top of the function and see if it works there. I doubt this will make any difference, but it's a cheap try ;)

**Comment by CaporalDead** [comment]
Hi @gebsl, sadly your proposal didn't work for me :(. I'm still investigating to find a way to make it works

**Comment by VadPinchuk** [comment]
Is this plugin works for iOS at all? 
I have found only registering method in ios files. no else.
So I have no idea how to start methods in iOS

**Comment by gebsl** [comment]
@VadPinchuk: Due to iOS restrictions, some methods only work on Android (like `registerOneOffTask`). But basically, the plugin works both for Android and iOS.

Kindly refer to the setup guide for each platform: https://github.com/vrtdev/flutter_workmanager#platform-setup

Apart from that, please don't use issues to ask general questions, as it does not contribute to resolving the specific issue, thanks. If there is anything unclear, create another github issue to discuss the topic.

**Comment by ened** [comment]
The issue seems to be resolved.
