### ISSUE TITLE
🐞[IOS] Unhandled Exception: MissingPluginException

### ISSUE THREAD

**Issue by rrifafauzikomara** [fluttercommunity/flutter_workmanager#205]
- [x] I have read the [README](https://github.com/vrtdev/flutter_workmanager/blob/master/README.md)
- [x] I have done the setup for [Android](https://github.com/vrtdev/flutter_workmanager/blob/master/ANDROID_SETUP.md)
- [x] I have done the setup for [iOS](https://github.com/vrtdev/flutter_workmanager/blob/master/IOS_SETUP.md)
- [x] I have ran the sample app and it does not work there

**Version**

| Technology           | Version       |
| -------------------  | ------------- |
| Workmanager version  |     X        |
| Xcode version        |       X        |
| Swift version        |      X         |
| iOS deployment target|       X        |

*Because I just clone the repository from here: https://github.com/fluttercommunity/flutter_workmanager and running it.

**Describe the error**
First, I just clone the repository, open on my Android Studio with version 4.0.1, open the simulator iPhone 11 Pro Max (Version 11.6 (921.9.1), SimulatorKit 581.9.1, CoreSimulator 704.12.2) and running it.

And this is the result:
[![enter image description here][1]][1]

And when I click the button "Start the Flutter background service" get this error:

  [1]: https://i.stack.imgur.com/cL6fE.png

```
Launching lib/main.dart on iPhone 11 Pro Max in debug mode...
Warning: Missing build name (CFBundleShortVersionString).
Warning: Missing build number (CFBundleVersion).
Action Required: You must set a build name and number in the pubspec.yaml file version field before submitting to the App Store.
Running pod install...
Warning: Podfile is out of date
  This can cause issues if your application depends on plugins that do not support iOS.
  See https://flutter.dev/docs/development/packages-and-plugins/developing-packages#plugin-platforms for details.
  If you have local Podfile edits you would like to keep, see https://github.com/flutter/flutter/issues/45197 for instructions.
To regenerate the Podfile, run:
  rm ios/Podfile

Running Xcode build...
Xcode build done.                                           23.2s
Waiting for iPhone 11 Pro Max to report its views...
Debug service listening on ws://127.0.0.1:64864/97WkupJ9Oas=/ws
Syncing files to device iPhone 11 Pro Max...
[VERBOSE-2:ui_dart_state.cc(166)] Unhandled Exception: MissingPluginException(No implementation found for method initialize on channel be.tramckrijte.workmanager/foreground_channel_work_manager)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:7)
<asynchronous suspension>
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:334:12)
#2      Workmanager.initialize (package:workmanager/src/workmanager.dart:100:30)
#3      _MyAppState.build.<anonymous closure> (package:workmanager_example/main.dart:87:33)
#4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:992:19)
#5      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1098:38)
#6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:184:24)
#7      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:524:11)
#8      BaseTapGestureRecognizer._checkUp (package:flu<…>
```

**Output of `flutter doctor -v`**

```
[✓] Flutter (Channel stable, 1.20.1, on Mac OS X 10.15.6 19G2021, locale en-US)
    • Flutter version 1.20.1 at /Users/rrifafauzikomara/Documents/flutter
    • Framework revision 2ae34518b8 (3 weeks ago), 2020-08-05 19:53:19 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/rrifafauzikomara/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[!] VS Code (version 1.47.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • Android SDK built for x86 (mobile) • emulator-5554
      • android-x86 • Android 10 (API 29) (emulator)
    • iPhone 11 Pro Max (mobile)         • FDF80209-3C4A-417F-BC21-3A9EA2B4FDCE
      • ios         • com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)

! Doctor found issues in 1 category.
```

**Comment by sanni-aubergine** [comment]
waiting for an update on this issue. I too am facing this on iOS.

**Comment by ZhuBoao** [comment]
same here

**Comment by kadahlin** [comment]
Same issue here, is there any update on this?

**Comment by darkh** [comment]
any update I have the same problem?

**Comment by angrys0n** [comment]
any update?

**Comment by yekkaplan** [comment]
Any update?

**Comment by sanni-aubergine** [comment]
Have you tried any other plugins which works correctly

**Comment by asmodeoux** [comment]
Unfortunately that's still an issue

**Comment by emouawad** [comment]
Same here

**Comment by ened** [comment]
Please open a new issue if this problem still exists using the beta version `0.5.0-dev.8`
