### ISSUE TITLE
MissingPluginException:  plugins.flutter.io/path_provider

### ISSUE THREAD

**Issue by VarmaTech** [fluttercommunity/flutter_workmanager#222]
| Technology           | Version       |
| -------------------  | ------------- |
| Workmanager version  |         0.2.2      | 
| path_provider  |         1.5.1     | 
| path  |         1.6.4     | 
| OS  |         android    | 

**Describe the error**
 i have job which should run in background , in the job in am trying to access path of StorageDirectory in which i am getting  below , but when i run on runtime no issue its works fine. when i run workmanager job only below error is coming.

```
Unhandled Exception: MissingPluginException(No implementation found for method getStorageDirectory 
on channel plugins.flutter.io/path_provider)
#4      AppDatabase._openDatabase package:furniturepos/database/app_database.dart:52
#5      AppDatabase.database package:furniturepos/database/app_database.dart:35
#6      AppImagesDao._db package:furniturepos/…/dao/dao_app_images.dart:11
#7      AppImagesDao.getAllImages package:furniturepos/…/dao/dao_app_images.dart:44
#8      AppImagesSync.imagesSyncfromdb package:furniturepos/…/jobs/app_sync_images_job.dart:9
#9      startJobs.<anonymous closure> package:furniturepos/jobs/web_background_jobs.dart:100
#10     Workmanager.executeTask.<anonymous closure>  package:workmanager/src/workmanager.dart:80
#11     MethodChannel._handleAsMethodCall package:flutter/…/services/platform_channel.dart:430
#12     MethodChannel.setMethodCallHandler.<anonymous closure> package:flutter/…/services/platform_channel.dart:383
#13     _DefaultBinaryMessenger.handlePlatformMessage package:flutter/…/services/binding.dart:283
#14     _invoke3.<anonymous closure>  (dart:ui/hooks.dart:280:15)
#15     _rootRun  (dart:async/zone.dart:1190:13)
#16     _CustomZone.run  (dart:async/zone.dart:1093:19)
#17     _CustomZone.runGuarded  (dart:async/zone.dart:997:7)
#18     _invoke3  (dart:ui/hooks.dart:279:10)
#19     _dispatchPlatformMessage  (dart:ui/hooks.dart:154:5)

```
**Output of `flutter doctor -v`**
```
[✓] Flutter (Channel stable, 1.22.0, on Mac OS X 10.15.6 19G2021, locale en-GB)
    • Flutter version 1.22.0 at /Volumes/MyData/Software/SDK/Flutter-SDK/flutter
    • Framework revision d408d302e2 (3 weeks ago), 2020-09-29 11:49:17 -0700
    • Engine revision 5babba6c4d
    • Dart version 2.10.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Volumes/MyData/Software/SDK/Android/SDK
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

[✓] Connected device (1 available)            
    • SM T830 (mobile)  • 192.168.29.221:5555 • android-arm64 • Android 10 (API 29)

• No issues found!
```

**Comment by vanlooverenkoen** [comment]
Make sure you have enabled v2 embedding. of set the plugin registrant callback.
for iOS the registrant callback should always be set.

**Comment by Nicolas-Medina-Teracode** [comment]
Hi @vanlooverenkoen ! I am having the same issue, could you more specific about your suggestion?

Thanks!

**Comment by ened** [comment]
Hi @VarmaTech, it looks like the setup has not been complete. Please look at the Android installation details here https://github.com/fluttercommunity/flutter_workmanager/blob/master/ANDROID_SETUP.md or https://github.com/fluttercommunity/flutter_workmanager/blob/master/ANDROID_SETUP_V1.md if your app uses the old embedding.
