### ISSUE TITLE
🐞[Android] java.lang.VerifyError: Verifier rejected class androidx.work.impl.OperationImpl

### ISSUE THREAD

**Issue by proninyaroslav** [fluttercommunity/flutter_workmanager#247]
- [x] I have read the [README](https://github.com/vrtdev/flutter_workmanager/blob/master/README.md)
- [x] I have done the setup for [Android](https://github.com/vrtdev/flutter_workmanager/blob/master/ANDROID_SETUP.md)
- [x] I have done the setup for [iOS](https://github.com/vrtdev/flutter_workmanager/blob/master/IOS_SETUP.md)
- [x] I have ran the sample app and it does not work there

**Version**

| Technology           | Version       |
| -------------------  | ------------- |
| Workmanager version  |      0.2.3         |
| Flutter version  |      2.0.0         |
| Kotlin version  |      1.4.31         |
| Android target version  |      11         |

**Describe the error**
I recently migrated my app to Flutter 2.0. The `workmanager` worked fine until I upgraded all app packages to the nullsafety option (`flutter pub upgrade --nullsafety`). Now if I try to run a onetime-worker an exception occurs:
```
E/AndroidRuntime( 6099): java.lang.VerifyError: Verifier rejected class androidx.work.impl.OperationImpl: com.google.common.util.concurrent.ListenableFuture androidx.work.impl.OperationImpl.getResult() failed to verify: com.google.common.util.concurrent.ListenableFuture androidx.work.impl.OperationImpl.getResult(): [0x2]  can't resolve returned type 'Unresolved Reference: com.google.common.util.concurrent.ListenableFuture' or 'Unresolved Reference: androidx.work.impl.utils.futures.SettableFuture' (declaration of 'androidx.work.impl.OperationImpl' appears in /data/app/~~UVZL9lLuZ7G6u08ofLVzBw==/com.myapp-BK3ugsfgz-p81PPUKdL3-g==/base.apk)
E/AndroidRuntime( 6099): 	at androidx.work.impl.utils.EnqueueRunnable.<init>(EnqueueRunnable.java:77)
E/AndroidRuntime( 6099): 	at androidx.work.impl.WorkContinuationImpl.enqueue(WorkContinuationImpl.java:186)
E/AndroidRuntime( 6099): 	at androidx.work.impl.WorkManagerImpl.enqueueUniqueWork(WorkManagerImpl.java:396)
E/AndroidRuntime( 6099): 	at androidx.work.WorkManager.enqueueUniqueWork(WorkManager.java:345)
E/AndroidRuntime( 6099): 	at be.tramckrijte.workmanager.WM.enqueueOneOffTask(WorkmanagerCallHandler.kt:139)
E/AndroidRuntime( 6099): 	at be.tramckrijte.workmanager.RegisterTaskHandler.enqueueOneOffTask(WorkmanagerCallHandler.kt:79)
E/AndroidRuntime( 6099): 	at be.tramckrijte.workmanager.RegisterTaskHandler.handle(WorkmanagerCallHandler.kt:57)
E/AndroidRuntime( 6099): 	at be.tramckrijte.workmanager.WorkmanagerCallHandler.handle(WorkmanagerCallHandler.kt:23)
E/AndroidRuntime( 6099): 	at be.tramckrijte.workmanager.WorkmanagerPlugin.onMethodCall(WorkmanagerPlugin.kt:42)
E/AndroidRuntime( 6099): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/AndroidRuntime( 6099): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/AndroidRuntime( 6099): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/AndroidRuntime( 6099): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/AndroidRuntime( 6099): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/AndroidRuntime( 6099): 	at android.os.Looper.loop(Looper.java:183)
E/AndroidRuntime( 6099): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/AndroidRuntime( 6099): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 6099): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/AndroidRuntime( 6099): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Output of `flutter pub deps`**
<details>
<summary>Dependency graph</summary>

```
|-- analyzer 1.1.0
|   |-- _fe_analyzer_shared 17.0.0
|   |   '-- meta...
|   |-- cli_util 0.3.0
|   |   |-- meta...
|   |   '-- path...
|   |-- convert 3.0.0
|   |   '-- typed_data...
|   |-- package_config 2.0.0
|   |   '-- path...
|   |-- args...
|   |-- collection...
|   |-- crypto...
|   |-- glob...
|   |-- meta...
|   |-- path...
|   |-- pub_semver...
|   |-- source_span...
|   |-- watcher...
|   '-- yaml...
|-- animate_icons 1.0.2
|   '-- flutter...
|-- backdrop 0.5.3
|   '-- flutter...
|-- barcode_widget 2.0.0
|   |-- barcode 2.1.0
|   |   |-- qr 2.0.0
|   |   |   '-- meta...
|   |   '-- meta...
|   '-- flutter...
|-- bloc 7.0.0-nullsafety.3
|   '-- meta 1.3.0
|-- bloc_test 8.0.0-nullsafety.1
|   |-- mocktail 0.0.1-dev.12
|   |   '-- matcher...
|   |-- test 1.16.5
|   |   |-- coverage 1.0.1
|   |   |   |-- source_maps 0.10.10
|   |   |   |   '-- source_span...
|   |   |   |-- vm_service 6.1.0+1
|   |   |   |-- args...
|   |   |   |-- logging...
|   |   |   |-- package_config...
|   |   |   |-- path...
|   |   |   '-- stack_trace...
|   |   |-- node_preamble 1.4.13
|   |   |-- shelf_packages_handler 3.0.0
|   |   |   |-- path...
|   |   |   |-- shelf...
|   |   |   '-- shelf_static...
|   |   |-- shelf_static 1.0.0
|   |   |   |-- convert...
|   |   |   |-- http_parser...
|   |   |   |-- mime...
|   |   |   |-- path...
|   |   |   '-- shelf...
|   |   |-- test_core 0.3.15
|   |   |   |-- source_map_stack_trace 2.1.0
|   |   |   |   |-- path...
|   |   |   |   |-- source_maps...
|   |   |   |   '-- stack_trace...
|   |   |   |-- analyzer...
|   |   |   |-- args...
|   |   |   |-- async...
|   |   |   |-- boolean_selector...
|   |   |   |-- collection...
|   |   |   |-- coverage...
|   |   |   |-- glob...
|   |   |   |-- io...
|   |   |   |-- matcher...
|   |   |   |-- meta...
|   |   |   |-- package_config...
|   |   |   |-- path...
|   |   |   |-- pedantic...
|   |   |   |-- pool...
|   |   |   |-- source_maps...
|   |   |   |-- source_span...
|   |   |   |-- stack_trace...
|   |   |   |-- stream_channel...
|   |   |   |-- test_api...
|   |   |   |-- vm_service...
|   |   |   '-- yaml...
|   |   |-- webkit_inspection_protocol 1.0.0
|   |   |   '-- logging...
|   |   |-- analyzer...
|   |   |-- async...
|   |   |-- boolean_selector...
|   |   |-- http_multi_server...
|   |   |-- io...
|   |   |-- js...
|   |   |-- package_config...
|   |   |-- path...
|   |   |-- pedantic...
|   |   |-- pool...
|   |   |-- shelf...
|   |   |-- shelf_web_socket...
|   |   |-- source_span...
|   |   |-- stack_trace...
|   |   |-- stream_channel...
|   |   |-- test_api...
|   |   |-- typed_data...
|   |   |-- web_socket_channel...
|   |   '-- yaml...
|   |-- bloc...
|   '-- meta...
|-- build_runner 1.11.5
|   |-- args 2.0.0
|   |-- async 2.5.0
|   |   '-- collection...
|   |-- build_daemon 2.1.8
|   |   |-- built_collection 5.0.0
|   |   |-- built_value 8.0.0
|   |   |   |-- fixnum 1.0.0
|   |   |   |-- built_collection...
|   |   |   '-- collection...
|   |   |-- http_multi_server...
|   |   |-- logging...
|   |   |-- path...
|   |   |-- pedantic...
|   |   |-- pool...
|   |   |-- shelf...
|   |   |-- shelf_web_socket...
|   |   |-- stream_transform...
|   |   |-- watcher...
|   |   '-- web_socket_channel...
|   |-- build_resolvers 1.5.4
|   |   |-- analyzer...
|   |   |-- build...
|   |   |-- crypto...
|   |   |-- graphs...
|   |   |-- logging...
|   |   |-- meta...
|   |   |-- package_config...
|   |   |-- path...
|   |   |-- pool...
|   |   '-- pub_semver...
|   |-- build_runner_core 6.1.10
|   |   |-- async...
|   |   |-- build...
|   |   |-- build_config...
|   |   |-- build_resolvers...
|   |   |-- collection...
|   |   |-- convert...
|   |   |-- crypto...
|   |   |-- glob...
|   |   |-- graphs...
|   |   |-- logging...
|   |   |-- meta...
|   |   |-- package_config...
|   |   |-- path...
|   |   |-- pedantic...
|   |   |-- pool...
|   |   |-- timing...
|   |   |-- watcher...
|   |   '-- yaml...
|   |-- code_builder 3.6.0
|   |   |-- built_collection...
|   |   |-- built_value...
|   |   |-- collection...
|   |   |-- matcher...
|   |   '-- meta...
|   |-- dart_style 1.3.14
|   |   |-- analyzer...
|   |   |-- args...
|   |   |-- path...
|   |   |-- pub_semver...
|   |   '-- source_span...
|   |-- glob 2.0.0
|   |   |-- async...
|   |   |-- collection...
|   |   |-- file...
|   |   |-- path...
|   |   |-- pedantic...
|   |   '-- string_scanner...
|   |-- graphs 0.2.0
|   |-- http_multi_server 2.2.0
|   |   '-- async...
|   |-- io 0.3.5
|   |   |-- meta...
|   |   |-- path...
|   |   '-- string_scanner...
|   |-- js 0.6.3
|   |-- logging 1.0.0
|   |-- pool 1.5.0
|   |   |-- async...
|   |   '-- stack_trace...
|   |-- pub_semver 2.0.0
|   |   '-- collection...
|   |-- pubspec_parse 0.1.8
|   |   |-- checked_yaml...
|   |   |-- json_annotation...
|   |   |-- pub_semver...
|   |   '-- yaml...
|   |-- shelf 1.0.0
|   |   |-- async...
|   |   |-- collection...
|   |   |-- http_parser...
|   |   |-- path...
|   |   |-- stack_trace...
|   |   '-- stream_channel...
|   |-- shelf_web_socket 0.2.4+1
|   |   |-- shelf...
|   |   |-- stream_channel...
|   |   '-- web_socket_channel...
|   |-- stack_trace 1.10.0
|   |   '-- path...
|   |-- stream_transform 2.0.0
|   |-- timing 0.1.1+3
|   |   '-- json_annotation...
|   |-- watcher 1.0.0
|   |   |-- async...
|   |   |-- path...
|   |   '-- pedantic...
|   |-- web_socket_channel 1.2.0
|   |   |-- async...
|   |   |-- crypto...
|   |   '-- stream_channel...
|   |-- yaml 3.1.0
|   |   |-- collection...
|   |   |-- source_span...
|   |   '-- string_scanner...
|   |-- build...
|   |-- build_config...
|   |-- collection...
|   |-- crypto...
|   |-- meta...
|   |-- mime...
|   |-- path...
|   '-- pedantic...
|-- circular_check_box 1.0.4
|   '-- flutter...
|-- connectivity 3.0.2
|   |-- connectivity_macos 0.2.0
|   |   '-- flutter...
|   |-- connectivity_platform_interface 2.0.1
|   |   |-- plugin_platform_interface 2.0.0
|   |   |   '-- meta...
|   |   |-- flutter...
|   |   '-- meta...
|   |-- flutter...
|   '-- meta...
|-- cupertino_icons 1.0.2
|-- diffutil_sliverlist 0.5.0-nullsafety.0
|   |-- diffutil_dart 2.0.0-nullsafety.0
|   '-- flutter...
|-- dotenv 3.0.0-nullsafety.0
|   |-- args...
|   '-- meta...
|-- enum_to_string 1.0.14
|-- equatable 2.0.0
|   |-- collection 1.15.0
|   '-- meta...
|-- expandable_page_view 1.0.3
|   '-- flutter...
|-- floor 1.0.0-nullsafety.0
|   |-- floor_annotation 1.0.0-nullsafety.0
|   |   '-- meta...
|   |-- path 1.8.0
|   |-- sqflite 2.0.0+2
|   |   |-- sqflite_common 2.0.0+1
|   |   |   |-- meta...
|   |   |   |-- path...
|   |   |   '-- synchronized...
|   |   |-- flutter...
|   |   '-- path...
|   |-- sqflite_common_ffi 2.0.0
|   |   |-- sqlite3 1.0.0
|   |   |   |-- ffi 1.0.0
|   |   |   |-- collection...
|   |   |   '-- meta...
|   |   |-- synchronized 3.0.0
|   |   |-- meta...
|   |   |-- path...
|   |   '-- sqflite_common...
|   |-- flutter...
|   '-- meta...
|-- floor_generator 1.0.0-nullsafety.0
|   |-- analyzer...
|   |-- build...
|   |-- build_config...
|   |-- code_builder...
|   |-- collection...
|   |-- floor_annotation...
|   |-- meta...
|   '-- source_gen...
|-- flutter 0.0.0
|   |-- characters 1.1.0
|   |-- sky_engine 0.0.99
|   |-- typed_data 1.3.0
|   |   '-- collection...
|   |-- vector_math 2.1.0
|   |-- collection...
|   '-- meta...
|-- flutter_bloc 7.0.0-nullsafety.3
|   |-- provider 5.0.0-nullsafety.5
|   |   |-- nested 1.0.0
|   |   |   '-- flutter...
|   |   |-- collection...
|   |   '-- flutter...
|   |-- bloc...
|   '-- flutter...
|-- flutter_linkify 5.0.0
|   |-- linkify 4.0.0
|   '-- flutter...
|-- flutter_localizations 0.0.0
|   |-- clock 1.1.0
|   |-- intl 0.17.0
|   |   |-- clock...
|   |   '-- path...
|   |-- characters...
|   |-- collection...
|   |-- flutter...
|   |-- meta...
|   |-- path...
|   |-- typed_data...
|   '-- vector_math...
|-- flutter_secure_storage 4.0.0
|   |-- flutter...
|   '-- meta...
|-- flutter_staggered_animations 0.1.3
|   '-- flutter...
|-- flutter_test 0.0.0
|   |-- boolean_selector 2.1.0
|   |   |-- source_span...
|   |   '-- string_scanner...
|   |-- charcode 1.2.0
|   |-- fake_async 1.2.0
|   |   |-- clock...
|   |   '-- collection...
|   |-- source_span 1.8.0
|   |   |-- charcode...
|   |   |-- collection...
|   |   |-- path...
|   |   '-- term_glyph...
|   |-- stream_channel 2.1.0
|   |   '-- async...
|   |-- string_scanner 1.1.0
|   |   |-- charcode...
|   |   '-- source_span...
|   |-- term_glyph 1.2.0
|   |-- test_api 0.2.19
|   |   |-- async...
|   |   |-- boolean_selector...
|   |   |-- collection...
|   |   |-- matcher...
|   |   |-- meta...
|   |   |-- path...
|   |   |-- source_span...
|   |   |-- stack_trace...
|   |   |-- stream_channel...
|   |   |-- string_scanner...
|   |   '-- term_glyph...
|   |-- async...
|   |-- characters...
|   |-- clock...
|   |-- collection...
|   |-- flutter...
|   |-- matcher...
|   |-- meta...
|   |-- path...
|   |-- stack_trace...
|   |-- typed_data...
|   '-- vector_math...
|-- fluttertoast 8.0.1-nullsafety.0
|   |-- flutter_web_plugins 0.0.0
|   |   |-- characters...
|   |   |-- collection...
|   |   |-- flutter...
|   |   |-- js...
|   |   |-- meta...
|   |   |-- typed_data...
|   |   '-- vector_math...
|   '-- flutter...
|-- freezed 0.14.0
|   |-- analyzer...
|   |-- build...
|   |-- build_config...
|   |-- freezed_annotation...
|   |-- meta...
|   '-- source_gen...
|-- freezed_annotation 0.14.0
|   |-- json_annotation 4.0.0
|   |-- collection...
|   '-- meta...
|-- http 0.13.0
|   |-- http_parser 4.0.0
|   |   |-- charcode...
|   |   |-- collection...
|   |   |-- source_span...
|   |   |-- string_scanner...
|   |   '-- typed_data...
|   |-- pedantic 1.11.0
|   |-- meta...
|   '-- path...
|-- injectable 1.2.0
|   '-- get_it 6.0.0
|       |-- async...
|       '-- collection...
|-- injectable_generator 1.2.0
|   |-- analyzer...
|   |-- build...
|   |-- code_builder...
|   |-- collection...
|   |-- dart_style...
|   |-- glob...
|   |-- injectable...
|   |-- path...
|   '-- source_gen...
|-- intl_utils 2.0.0
|   |-- archive 3.1.2
|   |   |-- crypto...
|   |   '-- path...
|   |-- petitparser 4.0.2
|   |   '-- meta...
|   |-- analyzer...
|   |-- args...
|   |-- http...
|   |-- intl...
|   |-- path...
|   '-- yaml...
|-- jiffy 4.0.0
|   '-- intl...
|-- json_serializable 4.0.2
|   |-- build 1.6.3
|   |   |-- analyzer...
|   |   |-- async...
|   |   |-- convert...
|   |   |-- crypto...
|   |   |-- glob...
|   |   |-- logging...
|   |   |-- meta...
|   |   '-- path...
|   |-- build_config 0.4.6
|   |   |-- checked_yaml 1.0.4
|   |   |   |-- json_annotation...
|   |   |   |-- source_span...
|   |   |   '-- yaml...
|   |   |-- json_annotation...
|   |   |-- meta...
|   |   |-- path...
|   |   |-- pubspec_parse...
|   |   '-- yaml...
|   |-- source_gen 0.9.10+3
|   |   |-- analyzer...
|   |   |-- async...
|   |   |-- build...
|   |   |-- dart_style...
|   |   |-- glob...
|   |   |-- meta...
|   |   |-- path...
|   |   |-- pedantic...
|   |   '-- source_span...
|   |-- analyzer...
|   |-- json_annotation...
|   |-- meta...
|   '-- path...
|-- json_serializable_generator 1.0.1
|   |-- build...
|   '-- meta...
|-- lint 1.5.2
|-- logger 1.0.0-nullsafety.0
|-- material_design_icons_flutter 4.0.5855
|   '-- flutter...
|-- mockito 5.0.0
|   |-- analyzer...
|   |-- build...
|   |-- code_builder...
|   |-- collection...
|   |-- dart_style...
|   |-- matcher...
|   |-- meta...
|   |-- path...
|   |-- source_gen...
|   '-- test_api...
|-- quiver 3.0.0
|   '-- matcher 0.12.10
|       '-- stack_trace...
|-- receive_sharing_intent 1.4.3
|   '-- flutter...
|-- responsive_builder 0.4.0-nullsafety.1
|   '-- flutter...
|-- share 2.0.0
|   |-- mime 1.0.0
|   |-- flutter...
|   '-- meta...
|-- shared_preferences 2.0.3
|   |-- shared_preferences_linux 2.0.0
|   |   |-- file 6.1.0
|   |   |   |-- meta...
|   |   |   '-- path...
|   |   |-- path_provider_linux 2.0.0
|   |   |   |-- xdg_directories 0.2.0
|   |   |   |   |-- process 4.1.0
|   |   |   |   |   |-- file...
|   |   |   |   |   |-- path...
|   |   |   |   |   '-- platform...
|   |   |   |   |-- meta...
|   |   |   |   '-- path...
|   |   |   |-- flutter...
|   |   |   |-- path...
|   |   |   '-- path_provider_platform_interface...
|   |   |-- flutter...
|   |   |-- meta...
|   |   |-- path...
|   |   '-- shared_preferences_platform_interface...
|   |-- shared_preferences_macos 2.0.0
|   |   |-- flutter...
|   |   '-- shared_preferences_platform_interface...
|   |-- shared_preferences_platform_interface 2.0.0
|   |   '-- flutter...
|   |-- shared_preferences_web 2.0.0
|   |   |-- flutter...
|   |   |-- flutter_web_plugins...
|   |   |-- meta...
|   |   '-- shared_preferences_platform_interface...
|   |-- shared_preferences_windows 2.0.0
|   |   |-- path_provider_platform_interface 2.0.1
|   |   |   |-- platform 3.0.0
|   |   |   |-- flutter...
|   |   |   |-- meta...
|   |   |   '-- plugin_platform_interface...
|   |   |-- path_provider_windows 2.0.0
|   |   |   |-- win32 2.0.0
|   |   |   |   '-- ffi...
|   |   |   |-- ffi...
|   |   |   |-- flutter...
|   |   |   |-- meta...
|   |   |   |-- path...
|   |   |   '-- path_provider_platform_interface...
|   |   |-- file...
|   |   |-- flutter...
|   |   |-- meta...
|   |   |-- path...
|   |   '-- shared_preferences_platform_interface...
|   |-- flutter...
|   '-- meta...
|-- smooth_page_indicator 0.3.0-nullsafety.0
|   '-- flutter...
|-- superellipse_shape 0.2.0-nullsafety.0
|   '-- flutter...
|-- url_launcher 6.0.2
|   |-- url_launcher_linux 2.0.0
|   |   '-- flutter...
|   |-- url_launcher_macos 2.0.0
|   |   '-- flutter...
|   |-- url_launcher_platform_interface 2.0.2
|   |   |-- flutter...
|   |   '-- plugin_platform_interface...
|   |-- url_launcher_web 2.0.0
|   |   |-- flutter...
|   |   |-- flutter_web_plugins...
|   |   |-- meta...
|   |   '-- url_launcher_platform_interface...
|   |-- url_launcher_windows 2.0.0
|   |   '-- flutter...
|   '-- flutter...
|-- uuid 3.0.1
|   '-- crypto 3.0.0
|       |-- collection...
|       '-- typed_data...
'-- workmanager 0.2.3
    '-- flutter...
```

</details>

**Output of `flutter doctor -v`**
```
[✓] Flutter (Channel stable, 2.0.0, on Linux, locale ru_RU.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] IntelliJ IDEA Community Edition (version 2020.3)
[✓] Connected device (3 available)
```

**Comment by proninyaroslav** [comment]
It turned out that the reason was this dependency, which was in my `build.gradle`. Once I added it to resolve a Guava version conflict, but now it created a problem:
```
implementation "com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava"
```
