### ISSUE TITLE
java.lang.RuntimeException: Unable to get provider androidx.work.impl.WorkManagerInitializer: java.lang.ClassNotFoundException: Didn't find class "androidx.work.impl.WorkManagerInitializer"

### ISSUE THREAD

**Issue by LostInDarkMath** [fluttercommunity/flutter_workmanager#260]
Hi there! Your library works fine for me on most devices, but it crashed on my Samsung GT-I9205 8Android 4.4.2. The app does not start and just prints "Unfortunately, MyApp has stopped". Do you have an idea what's going on here?

**Output of Logcat**
```
05-04 18:51:45.013 7717-7717/com.conngenial.conngenial E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.conngenial.conngenial, PID: 7717
    java.lang.RuntimeException: Unable to get provider androidx.work.impl.WorkManagerInitializer: java.lang.ClassNotFoundException: Didn't find class "androidx.work.impl.WorkManagerInitializer" on path: DexPathList[[zip file "/data/app/com.conngenial.conngenial-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.conngenial.conngenial-2, /vendor/lib, /system/lib]]
        at android.app.ActivityThread.installProvider(ActivityThread.java:5236)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:4828)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4711)
        at android.app.ActivityThread.access$1600(ActivityThread.java:175)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1368)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:146)
        at android.app.ActivityThread.main(ActivityThread.java:5602)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
        at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.work.impl.WorkManagerInitializer" on path: DexPathList[[zip file "/data/app/com.conngenial.conngenial-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.conngenial.conngenial-2, /vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:67)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
        at android.app.ActivityThread.installProvider(ActivityThread.java:5221)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:4828) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4711) 
        at android.app.ActivityThread.access$1600(ActivityThread.java:175) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1368) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:146) 
        at android.app.ActivityThread.main(ActivityThread.java:5602) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099) 
        at dalvik.system.NativeStart.main(Native Method) 
```
**Output of `flutter doctor -v`**
```
[√] Flutter (Channel stable, 2.0.6, on Microsoft Windows [Version 6.1.7601], locale de-DE)
    • Flutter version 2.0.6 at C:\flutter
    • Framework revision 1d9032c7e1 (5 days ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\WILLI\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.55.2)
    • VS Code at C:\Users\WILLI\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.22.0

[√] Connected device (2 available)
    • GT I9205 (mobile) • 096cb0b4 • android-arm    • Android 4.4.2 (API 19)
    • Chrome (web)      • chrome   • web-javascript • Google Chrome 90.0.4430.93

• No issues found!
```

**Comment by ened** [comment]
Interesting. WorkManager should be available & working on Android 4+. Will check.

**Comment by ened** [comment]
Attempting to test this on a 4.4 emulator caused https://github.com/flutter/flutter/issues/92137. Is this still needed, @LostInDarkMath

**Comment by LostInDarkMath** [comment]
Not really. Flutter has a lot of issues with such old android versions. Hopefully nobody uses this.
