### ISSUE TITLE
🐞[Android] "CancellationException: Task was cancelled" If run the same worker inside executeTask

### ISSUE THREAD

**Issue by proninyaroslav** [fluttercommunity/flutter_workmanager#265]
- [x] I have read the [README](https://github.com/vrtdev/flutter_workmanager/blob/master/README.md)
- [x] I have done the setup for [Android](https://github.com/vrtdev/flutter_workmanager/blob/master/ANDROID_SETUP.md)
- [x] I have done the setup for [iOS](https://github.com/vrtdev/flutter_workmanager/blob/master/IOS_SETUP.md)
- [x] I have ran the sample app and it does not work there

**Version**

| Technology           | Version       |
| -------------------  | ------------- |
| Workmanager version  |       0.4.4        |
| Xcode version        |               |
| Swift version        |               |
| iOS deployment target|               |

**Describe the error**
Steps to reproduce:
1. Run one-off worker from Flutter
2. Inside the running worker (inside `executeTask`), restart this worker with the same unique ID and the `ExistingWorkPolicy.replace` flag

After that, the following exception will happen:
```
I/WM-WorkerWrapper( 7610): Work [ id=bf3b2142-70a8-49b4-b9e6-79584377bf4c, tags={ be.tramckrijte.workmanager.BackgroundWorker } ] was cancelled
I/WM-WorkerWrapper( 7610): java.util.concurrent.CancellationException: Task was cancelled.
I/WM-WorkerWrapper( 7610): 	at androidx.work.impl.utils.futures.AbstractFuture.cancellationExceptionWithCause(AbstractFuture.java:1184)
I/WM-WorkerWrapper( 7610): 	at androidx.work.impl.utils.futures.AbstractFuture.getDoneValue(AbstractFuture.java:514)
I/WM-WorkerWrapper( 7610): 	at androidx.work.impl.utils.futures.AbstractFuture.get(AbstractFuture.java:475)
I/WM-WorkerWrapper( 7610): 	at androidx.work.impl.WorkerWrapper$2.run(WorkerWrapper.java:298)
I/WM-WorkerWrapper( 7610): 	at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
I/WM-WorkerWrapper( 7610): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
I/WM-WorkerWrapper( 7610): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
I/WM-WorkerWrapper( 7610): 	at java.lang.Thread.run(Thread.java:923)
```

Despite the exception, the planned worker will be launched anyway.

Example:
```Dart
import 'package:flutter/material.dart';
import 'package:workmanager/workmanager.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();

  Workmanager().initialize(
    callbackDispatcher,
    isInDebugMode: true,
  );
  runApp(MyApp());
}

const simpleTaskKey = "simpleTask";
const workId = '1';

void callbackDispatcher() {
  WidgetsFlutterBinding.ensureInitialized();

  Workmanager().executeTask((task, inputData) async {
    print('Run');
    await Workmanager().registerOneOffTask(
      workId,
      simpleTaskKey,
      initialDelay: Duration(minutes: 15),
      existingWorkPolicy: ExistingWorkPolicy.replace,
    );
    return true;
  });
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: Text("Flutter WorkManager Example"),
        ),
        body: Center(
          child: OutlinedButton(
            onPressed: () {
              Workmanager().registerOneOffTask(workId, simpleTaskKey);
            },
            child: Text('Run'),
          ),
        ),
      ),
    );
  }
}
```

**Output of `flutter doctor -v`**
```
[✓] Flutter (Channel stable, 2.0.6, on Linux, locale ru_RU.UTF-8)
    • Flutter version 2.0.6 at ***
    • Framework revision 1d9032c7e1 (2 недели назад), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at ***
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = ***
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_292-b10)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /usr/bin/chromium-freeworld

[✓] Linux toolchain - develop for Linux desktop
    • clang version 12.0.0 (Fedora 12.0.0-0.3.rc1.fc34)
    • cmake version 3.19.7
    • ninja version 1.10.2
    • pkg-config version 1.7.3

[✓] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at ***

[✓] Connected device (3 available)
    • sdk gphone x86 64 arm64 (mobile) • emulator-5554 • android-x64    • Android 11 (API 30) (emulator)
    • Linux (desktop)                  • linux         • linux-x64      • Linux
    • Chrome (web)                     • chrome        • web-javascript • Chromium 90.0.4430.85
```

**Comment by proninyaroslav** [comment]
P.S: This is a random problem, sometimes it completes without error, but more often than not an exception occurs.

**Comment by ened** [comment]
@proninyaroslav try assigning a different workId (always increasing).

**Comment by proninyaroslav** [comment]
@ened
But then `ExistingWorkPolicy.replace` will be no work, which should replace work with the same ID.

**Comment by ened** [comment]
@proninyaroslav Sounds like that would be ok because you are starting one off tasks anyway. 

Replacing work with the same Id may cause existing work to be cancelled, we would have to research a bit if this is intended behavior on Android WorkManager.

**Comment by proninyaroslav** [comment]
@ened 
Is the problem solved?

**Comment by janhelwich** [comment]
What I see is that there is a @pragma('vm:entry-point') missing as annotation on the callbackDispatcher.
