### ISSUE TITLE
WorkManager plugin does not work with any other plugins

### ISSUE THREAD

**Issue by shahbazhashmi** [fluttercommunity/flutter_workmanager#305]
- [x] I have read the [README](https://github.com/vrtdev/flutter_workmanager/blob/master/README.md)
- [x] I have done the setup for [Android](https://github.com/vrtdev/flutter_workmanager/blob/master/ANDROID_SETUP.md)
- [ ] I have done the setup for [iOS](https://github.com/vrtdev/flutter_workmanager/blob/master/IOS_SETUP.md)
- [ ] I have ran the sample app and it does not work there

**0.4.1**

The plugin is not working with below plugins.

- sqflite
- location
- connectivity

I have tried this https://stackoverflow.com/a/60207423/4685284. But no luck. 

      `class MyApplication: FlutterApplication(), PluginRegistry.PluginRegistrantCallback {

    private val TAG = "MyApplication"

    override fun onCreate() {
        super.onCreate()
         WorkmanagerPlugin.setPluginRegistrantCallback(this)
    }

    override fun registerWith(registry: PluginRegistry) {
        /*if (alreadyRegisteredWith(registry)) {
            return
        }*/
        WorkmanagerPlugin.registerWith(registry.registrarFor("be.tramckrijte.workmanager.WorkmanagerPlugin"));
        SqflitePlugin.registerWith(registry.registrarFor("com.tekartik.sqflite.SqflitePlugin"))
         //LocationPlugin.registerWith(registry.registrarFor("com.lyokone.location.LocationPlugin"))
        ConnectivityPlugin.registerWith(registry.registrarFor("io.flutter.plugins.connectivity.ConnectivityPlugin"))
    }

    private fun alreadyRegisteredWith(registry: PluginRegistry): Boolean {
        val key: String = TAG
        if (registry.hasPlugin(key)) {
            return true
        }
        registry.registrarFor(key)
        return false
    }
     }`

And below are the logs. Most of the methods of PluginRegistry are showing deprecated.

`E/WM-WorkerWrapper: Work [ id=7d678aa1-154f-434e-b5e7-818aa02c1789, tags={ be.tramckrijte.workmanager.BackgroundWorker } ] failed because it threw an exception/error
    java.util.concurrent.ExecutionException: java.lang.NullPointerException: registrar.context() must not be null
        at androidx.work.impl.utils.futures.AbstractFuture.getDoneValue(AbstractFuture.java:516)
        at androidx.work.impl.utils.futures.AbstractFuture.get(AbstractFuture.java:475)
        at androidx.work.impl.WorkerWrapper$2.run(WorkerWrapper.java:298)
        at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: java.lang.NullPointerException: registrar.context() must not be null
        at be.tramckrijte.workmanager.WorkmanagerPlugin$Companion.registerWith(WorkmanagerPlugin.kt:40)
        at xxxx.xxxxx.MyApplication.registerWith(MyApplication.kt:25)
        at be.tramckrijte.workmanager.BackgroundWorker.startWork(BackgroundWorker.kt:83)
        at androidx.work.impl.WorkerWrapper$1.run(WorkerWrapper.java:281)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:236)
        at android.app.ActivityThread.main(ActivityThread.java:8057)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)`

**Comment by beylmk** [comment]
I believe I'm seeing a similar issue... the problem is that this plugin calls (or somehow causes Flutter to call) `onDetachedFromEngine` once work completes, even if the app is in the foreground. It is recommended to dispose of plugin resources in this method (see doc here: https://api.flutter.dev/javadoc/io/flutter/embedding/engine/plugins/FlutterPlugin.html#onDetachedFromEngine-io.flutter.embedding.engine.plugins.FlutterPlugin.FlutterPluginBinding-). Therefore, this plugin leaves other plugins in a non-working state. 

Strangely, I see that `onAttachedToEngine` is called before `onDetachedFromEngine` once work completes.

**Comment by ened** [comment]
Please try to use `0.5.0-dev.8`. Note that this plugin creates a separate flutter engine when running, which then in turn starts it's own set of plugins. This should explain the logs (attached/detached). 

Please submit a example project to show the issue.
