### ISSUE TITLE
Network request fails in release mode

### ISSUE THREAD

**Issue by 0x-cell** [fluttercommunity/flutter_workmanager#314]
When using this package in release mode I'm getting constantly (network is present).
Library works great when running with debug notification.
```
09-13 15:49:26.991  1091 17797 I flutter : failed with SocketException: Failed host lookup: 'redacted.valid.webserver' (OS Error: No address associated with hostname, errno = 7) #0      _NativeSocket.startConnect (dart:io-patch/socket_patch.dart:677)
09-13 15:49:26.991  1091 17797 I flutter : #1      _RawSocket.startConnect (dart:io-patch/socket_patch.dart:1680)
09-13 15:49:26.991  1091 17797 I flutter : #2      RawSocket.startConnect (dart:io-patch/socket_patch.dart:27)
09-13 15:49:26.991  1091 17797 I flutter : #3      RawSecureSocket.startConnect (dart:io/secure_socket.dart:237)
09-13 15:49:26.991  1091 17797 I flutter : #4      SecureSocket.startConnect (dart:io/secure_socket.dart:60)
09-13 15:49:26.991  1091 17797 I flutter : #5      _ConnectionTarget.connect (dart:_http/http_impl.dart:2437)
09-13 15:49:26.991  1091 17797 I flutter : #6      _HttpClient._getConnection.connect (dart:_http/http_impl.dart:2805)
09-13 15:49:26.991  1091 17797 I flutter : #7      _HttpClient._getConnection (dart:_http/http_impl.dart:2810)
09-13 15:49:26.991  1091 17797 I flutter : #8      _HttpClient._openUrl (dart:_http/http_impl.dart:2694)
09-13 15:49:26.991  1091 17797 I flutter : #9      _HttpClient.openUrl (dart:_http/http_impl.dart:2568)
09-13 15:49:26.991  1091 17797 I flutter : #10     IOClient.send (package:http/src/io_client.dart:30)
09-13 15:49:26.991  1091 17797 I flutter : #11     BaseClient._sendUnstreamed (package:http/src/base_client.dart:93)
09-13 15:49:26.991  1091 17797 I flutter : #12     BaseClient.get (package:http/src/base
```

**Flutter sdk**
[√] Flutter (Channel stable, 2.5.0, on Microsoft Windows [Version 10.0.19042.1165], locale pl-PL)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[X] Chrome - develop for the web (Cannot find Chrome executable at
    .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[√] Android Studio (version 2020.3)
[√] VS Code (version 1.60.0)
[√] Connected device (2 available)

**version:**
workmanager: ^0.4.1

**tested on:**
Android 11

**Permissions**
```
<uses-permission android:name="android.permission.INTERNET"/>
<uses-permission android:name="com.android.vending.BILLING" />
```

**Comment by ened** [comment]
@0x-cell did you add the internet permission to `src/main` (instead of `src/debug`)/AndroidManifest.xml ?

**Comment by 0x-cell** [comment]
it was present in `src/main`.

**Comment by Luciferx86** [comment]
@0x-cell did you manage to rectify this?

**Comment by 0x-cell** [comment]
Yea, sorry. If i remember correctly i think that i did add the  `networkType: NetworkType.connected` constraint to make it work.
