### ISSUE TITLE
🐞[Enter Bug Description]

### ISSUE THREAD

**Issue by Bes79** [fluttercommunity/flutter_workmanager#343]
in some android devices after upgrade apk i get this error on statrtup, and app is crash

java.lang.IllegalAccessError: Illegal class access: 'androidx.room.v' attempting to access 'androidx.work.impl.u' (declaration of 'androidx.room.v' appears in base.apk)
at androidx.room.v.e(Unknown Source:15)
at b.h.a.k.e.onUpgrade(:2)
at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:398)
at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:298)
at b.h.a.k.e.s(Unknown Source:4)
at b.h.a.k.f.r(Unknown Source:4)
at androidx.room.s.c(Unknown Source:5)
at androidx.work.impl.utils.g.a(Unknown Source:25)
at androidx.work.impl.utils.g.run(Unknown Source:20)
at androidx.work.impl.utils.k.run(Unknown Source:2)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:764)

some times help reinstall, in some devices it is not help

**Comment by mikeesouth** [comment]
@Bes79 did you find any solution to this?

**Comment by Bes79** [comment]
unfortunately not, but I have a feeling that this is not from workmanager.

**Comment by ened** [comment]
Please use latest version `0.5.0-dev.8` and try again. If issue persists, please submit a sample project.

**Comment by MerdanDev** [comment]
Is there any update?
I have got very similar problem, but in my case I don't use workmanager, for me it's like third party dependencies use sqlite, and they have problem with version when upgrade.
Can you show what packages do you use, with versions?

**Comment by MerdanDev** [comment]
> unfortunately not, but I have a feeling that this is not from workmanager.

### Hello @Bes79, have you found any solution for it? 
I have very similar problem too.
