### ISSUE TITLE
🐞MissingPluginException getApplicationDocumentsDirectory

### ISSUE THREAD

**Issue by suhardiyan** [fluttercommunity/flutter_workmanager#345]
Hi i use workmanager workmanager v 0.3.0 and path_provider: 1.6.28,

I want to access local sqlite opendatabase (which is using path_provder) and do some function every 15 minutes.

When i start the apps, callbackDispatcher not running (stuck on await getApplicationDocumentsDirectory() function)

```
void callbackDispatcher() {
  Workmanager().executeTask((task, inputData) async {
    print("BEFORE APPLICATION DOCUMENT!");
    final document = getApplicationDocumentsDirectory();
    print("AFTER APPLICATION DOCUMENT!");
    //ALWAYS ERROR
    print(await document.path);
    print(document.then((value) => print("DADADADADADA")));
    print("AFTER APPLICATION DOCUMENT!");
    DbPresences dbPresence = DbPresences();

    DateTime now = DateTime.now();
    String formattedDate = DateFormat('yyyy-MM-dd').format(now);
    
    dbPresence.getCountAttendanceLocal(formattedDate);

    AwesomeNotifications().createNotification(
      content: NotificationContent(
        id: 1,
        channelKey: 'key1',
        title: 'Reminder Absensi',
        body: 'Anda belum melakukan absen, silahkan lakukan absen pada aplikasi KGIS'
      )
    );
    return Future.value(true);
  });
}
```

 My main workmanager function is :
 ```
 await Workmanager().initialize(
    callbackDispatcher, // The top level function, aka callbackDispatcher
    isInDebugMode: false // This should be false
  );

  await Workmanager().cancelAll();

  await Workmanager().registerPeriodicTask(
      "2", 
      "simplePeriodicTask",
      frequency: Duration(minutes: 15),
  );
```

The error is : 
```
E/flutter (13412): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method getApplicationDocumentsDirectory on channel plugins.flutter.io/path_provider)
E/flutter (13412): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157:7)  
E/flutter (13412): <asynchronous suspension>                                                                       
E/flutter (13412): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)  
E/flutter (13412): #2      MethodChannelPathProvider.getApplicationDocumentsPath (package:path_provider_platform_interface/src/method_channel_path_provider.dart:50:10)
E/flutter (13412): #3      getApplicationDocumentsDirectory (package:path_provider/path_provider.dart:104:39)      
E/flutter (13412): #4      callbackDispatcher.<anonymous closure> (package:bpjtteknik/main.dart:67:22)             
E/flutter (13412): #5      Workmanager.executeTask.<anonymous closure> (package:workmanager/src/workmanager.dart:89:28)
E/flutter (13412): #6      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:430:55)
E/flutter (13412): #7      MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:383:34)
E/flutter (13412): #8      _DefaultBinaryMessenger.handlePlatformMessage (package:flutter/src/services/binding.dart:283:33)
E/flutter (13412): #9      _invoke3.<anonymous closure> (dart:ui/hooks.dart:280:15)                                
E/flutter (13412): #10     _rootRun (dart:async/zone.dart:1190:13)                                                 
E/flutter (13412): #11     _CustomZone.run (dart:async/zone.dart:1093:19)                                          
E/flutter (13412): #12     _CustomZone.runGuarded (dart:async/zone.dart:997:7)                                     
E/flutter (13412): #13     _invoke3 (dart:ui/hooks.dart:279:10)                                                    
E/flutter (13412): #14     _dispatchPlatformMessage (dart:ui/hooks.dart:154:5) 
```

Please help, can somebody give me a fix?

**Comment by ened** [comment]
Please use the latest version (`0.5.0-dev.8`).

**Comment by TommasoAzz** [comment]
> Please use the latest version (`0.5.0-dev.8`).

Hi @ened to me right now it's not working with 0.5.0-dev.8 and I have the exact same problem.

**Comment by sirmamedical** [comment]
@TommasoAzz and @ened, I still can't make this work. I posted the details here: https://github.com/fluttercommunity/flutter_workmanager/issues/366#issuecomment-1061569224
