### ISSUE TITLE
Instant crash on emulator S - FLAG_MUTABLE 

### ISSUE THREAD

**Issue by adrianvintu** [fluttercommunity/flutter_workmanager#352]
Simply adding  `workmanager: ^0.4.1` to the pubspec.yaml with no dart code, will crash the app on startup

```
2022-01-07 21:59:42.062 14721-14772/com.wind_method E/AndroidRuntime: FATAL EXCEPTION: pool-23-thread-1
    Process: com.wind_method, PID: 14721
    java.lang.IllegalArgumentException: com.wind_method: Targeting S+ (version 10000 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
        at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
        at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:645)
        at android.app.PendingIntent.getBroadcast(PendingIntent.java:632)
        at androidx.work.impl.utils.ForceStopRunnable.getPendingIntent(ForceStopRunnable.java:196)
        at androidx.work.impl.utils.ForceStopRunnable.isForceStopped(ForceStopRunnable.java:128)
        at androidx.work.impl.utils.ForceStopRunnable.run(ForceStopRunnable.java:93)
        at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:920)
```

The fix seems pretty easy, something like this:

```
        var flags = PendingIntent.FLAG_UPDATE_CURRENT
        if (Build.VERSION.SDK_INT >= 23) {
            flags = flags or PendingIntent.FLAG_IMMUTABLE
        }

        return PendingIntent.getActivity(context, 0, intent, flags)
```

Can you maybe set this a high priority? It seems important and easy to fix.

**Comment by maxluetkemeyer** [comment]
https://github.com/flutter/flutter/issues/93609#issuecomment-968517299

Fixed it for me

**Comment by ened** [comment]
Please use `0.5.0-dev.7`.
