### ISSUE TITLE
🐞app crash when  im running the background task.

### ISSUE THREAD

**Issue by dafinoer** [fluttercommunity/flutter_workmanager#362]
- [x] I have read the [README](https://github.com/vrtdev/flutter_workmanager/blob/master/README.md)
- [x] I have done the setup for [Android](https://github.com/vrtdev/flutter_workmanager/blob/master/ANDROID_SETUP.md)
- [x] I have done the setup for [iOS](https://github.com/vrtdev/flutter_workmanager/blob/master/IOS_SETUP.md)
- [x] I have ran the sample app and it does not work there

**Version**

| Technology           | Version       |
| -------------------  | ------------- |
| Workmanager version  |      0.4.1         |
| Xcode version        |               |
| Swift version        |               |
| iOS deployment target|               |

**Describe the error**
im using flutter 2.10.0 and the app crash when i try to execute the code `Workmanager().registerOneOffTask('1', upload_avatar);`

**Output of `flutter doctor -v`**
```
D/AndroidRuntime(13296): Shutting down VM
I/WM-WorkerWrapper(13296): Worker result SUCCESS for Work [ id=71f63826-d673-4fd8-b48e-4a41b52a4091, tags={ be.tramckrijte.workmanager.BackgroundWorker } ]
E/AndroidRuntime(13296): FATAL EXCEPTION: main
E/AndroidRuntime(13296): Process: com.gocuit.cuit.dev, PID: 13296
E/AndroidRuntime(13296): kotlin.UninitializedPropertyAccessException: lateinit property channel has not been initialized
E/AndroidRuntime(13296): 	at com.ko2ic.imagedownloader.ImageDownloaderPlugin.tearDown(ImageDownloaderPlugin.kt:120)
E/AndroidRuntime(13296): 	at com.ko2ic.imagedownloader.ImageDownloaderPlugin.onDetachedFromEngine(ImageDownloaderPlugin.kt:71)
E/AndroidRuntime(13296): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.remove(FlutterEngineConnectionRegistry.java:273)
E/AndroidRuntime(13296): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.remove(FlutterEngineConnectionRegistry.java:283)
E/AndroidRuntime(13296): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.removeAll(FlutterEngineConnectionRegistry.java:291)
E/AndroidRuntime(13296): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.destroy(FlutterEngineConnectionRegistry.java:121)
E/AndroidRuntime(13296): 	at io.flutter.embedding.engine.FlutterEngine.destroy(FlutterEngine.java:425)
E/AndroidRuntime(13296): 	at be.tramckrijte.workmanager.BackgroundWorker.stopEngine$lambda-0(BackgroundWorker.kt:120)
E/AndroidRuntime(13296): 	at be.tramckrijte.workmanager.BackgroundWorker.lambda$LGzaYI9wpKnhzseAeQsBr_odg9A(Unknown Source:0)
E/AndroidRuntime(13296): 	at be.tramckrijte.workmanager.-$$Lambda$BackgroundWorker$LGzaYI9wpKnhzseAeQsBr_odg9A.run(Unknown Source:2)
E/AndroidRuntime(13296): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime(13296): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(13296): 	at android.os.Looper.loop(Looper.java:246)
E/AndroidRuntime(13296): 	at android.app.ActivityThread.main(ActivityThread.java:8653)
E/AndroidRuntime(13296): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(13296): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
E/AndroidRuntime(13296): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
I/Process (13296): Sending signal. PID: 13296 SIG: 9
```

**Comment by Bilalsk** [comment]
I had the same issue solved it by removing image_downloader.

**Comment by ened** [comment]
That is a bug with `image_downloader` - it needs to be adopted to work generically with non-Activity engines as well.
