### ISSUE TITLE
[Doc] IOS Backgroung processing didn't work on simulator

### ISSUE THREAD

**Issue by EA-YOUHOU** [fluttercommunity/flutter_workmanager#397]
- [x] I have read the [README](https://github.com/vrtdev/flutter_workmanager/blob/master/README.md)
- [x] I have done the setup for [Android](https://github.com/vrtdev/flutter_workmanager/blob/master/ANDROID_SETUP.md)
- [x] I have done the setup for [iOS](https://github.com/vrtdev/flutter_workmanager/blob/master/IOS_SETUP.md)
- [x] I have ran the sample app and it does not work there

**Version**

| Technology           | Version       |
| -------------------  | ------------- |
| Workmanager version  |               |
| Xcode version        |               |
| Swift version        |               |
| iOS deployment target|               |

**Describe the error**
https://developer.apple.com/documentation/backgroundtasks/bgtaskscheduler/error/code/unavailable
The doc should mention : 
```app running on Simulator doesn’t support background processing.```

![Capture d’écran 2022-06-02 à 13 55 50](https://user-images.githubusercontent.com/92172436/171624050-af5945cd-9b3c-4f78-ae19-67e6ea020697.png)

Else this error will appear :

```
flutter: PlatformException(bgTaskSchedulingFailed(Error Domain=BGTaskSchedulerErrorDomain Code=1 "(null)") error, Scheduling the task using BGTaskScheduler has failed.

This may be due to too many tasks being scheduled but not run.

See the error for details: Error Domain=BGTaskSchedulerErrorDomain Code=1 "(null)"., null, null)
flutter: 
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:177:18)
<asynchronous suspension>
#2      Workmanager.registerOneOffTask (package:workmanager/src/workmanager.dart:186:7)
<asynchronous suspension>

```

**Output of `flutter doctor -v`**

**Comment by LucasGois1** [comment]
This bug was fixed? I have the same problem

**Comment by ened** [comment]
The docs now cover this: `docs/debugging.mdx` explicitly notes that the simulator does not support background tasks and testing should be done on a physical device. The `bgTaskSchedulingFailed` / Code 1 error you saw is exactly the simulator limitation. Closing as addressed by the docs; testing instructions are at docs/debugging.mdx.
