### ISSUE TITLE
Unhandled Exception: PlatformException(unhandledMethod("registerOneOffTask") error, Unhandled method registerOneOffTask, null, null)

### ISSUE THREAD

**Issue by ibrahimcss** [fluttercommunity/flutter_workmanager#401]
- [x] I have read the [README](https://github.com/vrtdev/flutter_workmanager/blob/master/README.md)
- [x] I have done the setup for [Android](https://github.com/vrtdev/flutter_workmanager/blob/master/ANDROID_SETUP.md)
- [x] I have done the setup for [iOS](https://github.com/vrtdev/flutter_workmanager/blob/master/IOS_SETUP.md)
- [x] I have ran the sample app and it does not work there

**Version**

| Technology           | Version       |
| -------------------  | ------------- |
| Workmanager version  |       ^0.5.0       |
| Xcode version        |          13.3.1      |
| Swift version        |               |
| iOS deployment target|     13          |

**Describe the error**
Describe error
Optionally provide the least amount of code that shows this behaviour. Ideally in the `sample` app.

**Output of `flutter doctor -v`**

**Comment by mcleaw** [comment]
please check your appdelegate.swift maybe u forgot to register the task

**Comment by AdamBridges** [comment]
@ibrahimcss or @selimq did you find a solution for this? I'm encountering this error and have been unable to determine the source yet.

Error details:
```
flutter: PlatformException(unhandledMethod("registerOneOffTask") error, Unhandled method registerOneOffTask, null, null)
flutter: 
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:296:18)
<asynchronous suspension>
#2      Workmanager.registerOneOffTask (package:workmanager/src/workmanager.dart:192:7)
<asynchronous suspension>
```

Here's what I'm calling and doing so on a real iphone:
```
inputData ??= {};
inputData.addAll({
      taskKey : uniqueTaskName,
      tagKey : retryProcessTag
    });
await Workmanager().registerOneOffTask(
        "task-identifier",
        "retryProcess", // Ignored on iOS
        initialDelay: Duration(minutes: 30),
        constraints: Constraints(
          // connected or metered mark the task as requiring internet
          networkType: NetworkType.connected,
          // require external power
          requiresCharging: true,
        ),
        inputData: inputData // fully supported
    );
```

**Comment by ened** [comment]
This error comes from the plugin's old method-channel implementation not being able to resolve `registerOneOffTask` — typically a version mismatch between the workmanager package and the native code in your project (e.g. a stale `Podfile.lock`/build, or a very old plugin version).

The plugin was rewritten on Pigeon in 0.9.0 (#613), which replaced these method channels entirely. Upgrading to the latest release (0.9.0+) and doing a clean rebuild (`flutter clean`, re-run `pod install`) resolves it. One commenter in #650 confirmed the same fix by upgrading to 0.9.0+3.

Closing as resolved in current releases — please reopen with the exact plugin and Flutter versions if it reproduces on 0.9.0+.
