### ISSUE TITLE
Unable to play song with oneofftask or Periodic task while using justaudio package

### ISSUE THREAD

**Issue by DanielChuDC** [fluttercommunity/flutter_workmanager#411]
Hi I would like to ask if is it possible to schedule song using workmanager? I have tested the justaudio package set up with my app, normal play is fine. When I am trying to schedule it, the log seem fine but no song is played. Please kindly find the attached logs for your reference. Thank you!

```
@pragma('vm:entry-point')  // Mandatory if the App is obfuscated or using Flutter 3.1+
void callbackDispatcher() {
  Workmanager().executeTask((task, inputData) async {
    final audioPlayer = OneAudioPlayer();
    var logger = Logger();

    logger.d("Logger is working!");
    switch (task) {
      case simpleTaskKey:
        try { //add code execution
          final path =  inputData?['path']!;
          print("$simpleTaskKey was executed. inputData = $path}");
          Logger().e(path);
          audioPlayer.play(path);
        } catch(err) {
          print(err);
          Logger().e(err.runtimeType.toString());  // Logger flutter package, prints error on the debug console
          throw Exception(err);
        }

...

```

### Log

```
I/flutter (29573): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (29573): │ #0   callbackDispatcher.<anonymous closure> (path/app/data/services/background_work_manager.dart:24:12)
I/flutter (29573): │ #1   callbackDispatcher.<anonymous closure> (path/app/data/services/background_work_manager.dart:20:29)
I/flutter (29573): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (29573): │ 🐛 Logger is working!
I/flutter (29573): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (29573): rExample.simpleTask was executed. inputData = /path/Sugar pie.m4a}
I/flutter (29573): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (29573): │ #0   callbackDispatcher.<anonymous closure> (path/app/data/services/background_work_manager.dart:30:20)
I/flutter (29573): │ #1   callbackDispatcher.<anonymous closure> (path/app/data/services/background_work_manager.dart:20:29)
I/flutter (29573): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (29573): │ ⛔ /path/Sugar pie.m4a
I/flutter (29573): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (29573):  one audio player class playing /path/Sugar pie.m4a

```

### Flutter doctor
[✓] Flutter (Channel stable, 3.0.0, on macOS 12.4 darwin-x64, localeen-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.69.0)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

### Package version
  workmanager: ^0.5.0 
  just_audio: ^0.9.24

**Comment by ened** [comment]
1. Try awaiting the end of the song. Without it, the background process will end before the song even starts.
2. Have you got all the permissions?
3. Consider this plugin only to be used for very short audio clips, if any. You can refer to other background-audio plugins.

**Comment by DanielChuDC** [comment]
Hi @ened ! Thank you for your advice! 

I have tried:
1. Try awaiting the end of the song. 
2. I have gotten all the permission (since justaudio can play song normally when I click play button.)

Would like to understand how to adjust the elapsed time to a longer time or any way to check if the background process are able to access speaker ?
```
Result: Success
dartTask: Example.simpleTask
inputData: {"": ""}
Elapsed time: 1 seconds.
```
