### ISSUE TITLE
🐞[Android] Cancelling a task or setting `ExistingWorkPolicy.replace` destroys a platform channel of another library: webView 

### ISSUE THREAD

**Issue by clangenb** [fluttercommunity/flutter_workmanager#430]
- [x] I have read the [README](https://github.com/vrtdev/flutter_workmanager/blob/master/README.md)
- [x] I have done the setup for [Android](https://github.com/vrtdev/flutter_workmanager/blob/master/ANDROID_SETUP.md)
- [x] I have done the setup for [iOS](https://github.com/vrtdev/flutter_workmanager/blob/master/IOS_SETUP.md)
- [x] I have ran the sample app and it does not work there

**Version**

| Technology           | Version       |
| -------------------  | ------------- |
| Workmanager version  |    5.0.0        |

**Describe the error**
Cancelling a registered task by one of the provides methods or setting `ExistingWorkPolicy.replace` leads to the following error of the other lib I use.

```
E/flutter (17528): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method evaluateJavascript on channel com.pichillilorenzo/flutter_inappwebview_1214122967374174233124163190134233129107185174)
E/flutter (17528): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:294:7)
E/flutter (17528): <asynchronous suspension>
E/flutter (17528): #1      InAppWebViewController.evaluateJavascript (package:flutter_inappwebview/src/in_app_webview/in_app_webview_controller.dart:1420:16)
E/flutter (17528): <asynchronous suspension>
E/flutter (17528): 
```

I am quite positive that this is the issue because the `flutter_inappwebView` is launched correctly and works, but after initializing the workmanager, the above error is thrown.

**Output of `flutter doctor -v`**
[√] Flutter (Channel stable, 3.3.2, on Microsoft Windows [Version 10.0.22000.978], locale en-CH)
    • Flutter version 3.3.2 on channel stable at C:\tools\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e3c29ec00c (2 weeks ago), 2022-09-14 08:46:55 -0500
    • Engine revision a4ff2c53d8
    • Dart version 2.18.1
    • DevTools version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\Users\clang\AppData\Local\Android\sdk
    • Platform android-33, build-tools 32.0.0
    • Java binary at: C:\Users\clang\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-1\213.7172.25.2211.8571212\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2021.3)
    • Android Studio at C:\Users\clang\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-1\213.6777.52.2113.8172706
    • Flutter plugin version 64.1.4
    • Dart plugin version 213.5744.122
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] Android Studio (version 2022.1)
    • Android Studio at C:\Users\clang\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-1\213.7172.25.2211.8571212
    • Flutter plugin version 70.0.3
    • Dart plugin version 213.7371
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] Connected device (6 available)
    • Mi 9T (mobile)                     • 3d64a078         • android-arm64  • Android 10 (API 29)
    • SM G800F (mobile)                  • 52009a2368692331 • android-arm    • Android 6.0.1 (API 23)
    • Android SDK built for x86 (mobile) • emulator-5554    • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)                  • windows          • windows-x64    • Microsoft Windows [Version 10.0.22000.978]
    • Chrome (web)                       • chrome           • web-javascript • Google Chrome 105.0.5195.127
    • Edge (web)                         • edge             • web-javascript • Microsoft Edge 105.0.1343.50

[√] HTTP Host Availability
    • All required HTTP hosts are available

**Comment by clangenb** [comment]
The cause seems to be different. It is the actual execution of the `callBackDispatcher`, whichthat destroys the channel

**Comment by dominicmh** [comment]
We faced a similar issue. Just instead of `in_app_webview` it kills the BLE connection of `flutter_reactive_ble`.
Apparently, the [engine?.destroy()](https://github.com/fluttercommunity/flutter_workmanager/blob/370df0ca98735ab27594059e433b307e0992885e/android/src/main/kotlin/dev/fluttercommunity/workmanager/BackgroundWorker.kt#L142) in `BackgroundWorker.kt` is responsible for this. Removing this line fixes this issue. @clangenb, if you're still facing this issue with `in_app_webview`, can you confirm?

What's the purpose of destroying the engine? Since other platform channels seem to reuse it, is it possible it should be created differently?

**Comment by clangenb** [comment]
We have stopped using the workmanager and the webview since a long time now, so I can't make a statement unfortunately.

**Comment by ened** [comment]
Status (maintainer sweep, 2026-08): investigated against current main. The background engine is still destroyed via `engine?.destroy()` when the work completes (BackgroundWorker.stopEngine), and `destroy()` detaches the engine's plugin instances — which for plugins holding process-wide native singletons (the reported BLE/WebView cases) can tear down state that the main engine still needs. That's partly a plugin-lifecycle design question: the background engine is a separate engine, and plugin authors should treat per-engine detach as per-engine. We'd like a repro against a current version (0.9.1+1) before changing engine teardown, since leaving engines alive would leak memory. Keeping open; a minimal repro (e.g. flutter_reactive_ble + periodic task) would let us verify whether anything changed after the federated migration.

**Comment by ened** [comment]
Not actionable without a repro — investigated against current main (0.10.x): each callback runs in a dedicated background engine that is destroyed via `engine?.destroy()` when the work completes, which detaches that engine's plugin instances. Plugins holding process-wide native singletons (the reported BLE / in-app-webview cases) are affected by design; this is inherent to the per-task engine lifecycle, not a regression, and keeping engines alive would leak memory. The reporter has since moved off workmanager and can no longer provide a repro. Closing as answered/stale — reopen with a minimal repro (e.g. flutter_reactive_ble + periodic task) against 0.10.x if still affected.
