### ISSUE TITLE
java.lang.NullPointerException while app is in backeground around 2 hours than it's getting crashed

### ISSUE THREAD

**Issue by AnilNeodove** [fluttercommunity/flutter_workmanager#527]
Exception java.lang.NullPointerException: Attempt to read from field 'java.lang.String io.flutter.view.FlutterCallbackInformation.callbackLibraryPath' on a null object reference in method 'java.lang.String io.flutter.embedding.engine.dart.DartExecutor$DartCallback.toString()'
  at io.flutter.embedding.engine.dart.DartExecutor$DartCallback.toString
  at java.lang.String.valueOf (String.java:3657)
  at java.lang.StringBuilder.append (StringBuilder.java:132)
  at io.flutter.embedding.engine.dart.DartExecutor.executeDartCallback (DartExecutor.java)
  at dev.fluttercommunity.workmanager.BackgroundWorker.startWork$lambda$2 (BackgroundWorker.java)
  at dev.fluttercommunity.workmanager.BackgroundWorker.$r8$lambda$6sAKdFC7OiSIMKEvQJlu-u6nOVw (BackgroundWorker.java)
  at dev.fluttercommunity.workmanager.BackgroundWorker$$InternalSyntheticLambda$0$1db8b4055b41dbc6f5c5036cb185dab072c44060566ef8e5438a5c3ef071948c$0.run$bridge (BackgroundWorker.java)
  at android.os.Handler.handleCallback (Handler.java:942)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loopOnce (Looper.java:226)
  at android.os.Looper.loop (Looper.java:313)
  at android.app.ActivityThread.main (ActivityThread.java:8762)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:604)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1067)

**Comment by xiaolongwuhpu** [comment]
version 0.5.2  
 Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'java.lang.String io.flutter.view.FlutterCallbackInformation.callbackLibraryPath' on a null object reference in method 'java.lang.String nd.a$b.toString()'
       at nd.a$b.toString(:22)
       at java.lang.String.valueOf(String.java:4092)
       at java.lang.StringBuilder.append(StringBuilder.java:179)
       at nd.a.j(:28)
       at dev.fluttercommunity.workmanager.BackgroundWorker.w(:123)
       at dev.fluttercommunity.workmanager.BackgroundWorker.o()
       at id.a.run(:2)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:241)
       at android.os.Looper.loop(Looper.java:342)
       at android.app.ActivityThread.main(ActivityThread.java:8118)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:583)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)

**Comment by xiaolongwuhpu** [comment]
![image](https://github.com/fluttercommunity/flutter_workmanager/assets/13296347/5c9caf3d-e506-490b-b5b1-576260257b78)

**Comment by Ansis100** [comment]
Any updates on this? I haven't been able to reproduce the error, but I keep receiving Crashlytics reports of the exact same trace as @xiaolongwuhpu. 

Side note - _all_ of them are from Samsung devices.

**Comment by jonathanduke** [comment]
I started getting this error after upgrading the plugin from 0.5.x to 0.8.0 recently. I submitted a fix in PR #615, but in the meantime, a workaround to prevent it from crashing might be to delete the preferences file that contains the invalid handle at `<YOUR_APP>/shared_prefs/flutter_workmanager_plugin.xml`

**Comment by ened** [comment]
This is the same NPE as #650, which is fixed on main and shipped in **0.9.1+1** (#678, #681): `BackgroundWorker` now checks `FlutterCallbackInformation.lookupCallbackInformation(...)` for null (and hardens `FlutterInjector`/`FlutterLoader` init) and fails the work gracefully instead of crashing with `callbackLibraryPath` NPE. The stored callback handle is only invalidated by app updates/rebuilds that move the entrypoint; a stale `flutter_workmanager_plugin.xml` was the common trigger. Please upgrade to `workmanager: ^0.9.1+1` — closing as fixed.
